### ISSUE TITLE
Add flow typechecking

### ISSUE THREAD

**Issue by cezarneaga** [gov-ithub/socent-frontend#7]
### Expected behavior
Add flow typechecking: learn more: https://github.com/ryyppy/flow-guide
### Actual behavior
no typechecking
### Steps to reproduce the problem.
... 😴

**Comment by ClaudiuCeia** [comment]
Dacă nu faci tu, sau nu găsești pe nimeni, feel free să îmi dai assign :)

**Comment by cezarneaga** [comment]
De adaugat l-am adaugat deja nu e bai. la rezolvat erorile de flow am nevoie de ajutor. :) 
Trebuie invatat. daca faci un mini-curs super.
